config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :hospitals do

    member do
      post :create_doctor
      delete :delete_doctor
    end
    resources :patients
  end

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :treatable, polymorphic: true

  validates :dr_name, presence: :true
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :patients
  has_many :doctors, as: :treatable

  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :patient
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :hospital
  has_many :medications

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :dob,
  date: { before: Proc.new { Date.today }, message: 'Must be valid date' },
  on: :create
  validates :reason, presence: true
  validates :gender, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController

  def index
    @hospitals = Hospital.all
  end

  def show
    @hospital = Hospital.find params[:id]
    @doctor = @hospital.doctors.new
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.create hospital_params
    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully added!' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @hospital = Hospital.find params[:id]
  end

  def update
    @hospital = Hospital.find params[:id]
    @hospital.update_attributes hospital_params
    redirect_to hospital_path(@hospital)
  end

  def destroy
    @hospital = Hospital.find params[:id]
    @hospital.delete
    redirect_to hospitals_path
  end

  def create_doctor
    @hospital = Hospital.find params[:id]
    @hospital.doctors.create doctor_params
    redirect_to hospital_path(@hospital)
  end

  def delete_doctor
    @hospital = Hospital.find params[:id]
    @doctor = Doctor.find params[:doctor_id]
    @doctor.delete
    redirect_to @hospital
  end

  private
  def hospital_params
    params.require(:hospital).permit(:name, :address, :description)
  end

  def doctor_params
    params.require(:doctor).permit(:dr_name)
  end
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :find_patient, only: 
         [:show, :edit, :update, :destroy]

  def index
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.all
  end

  def show
    @hospital = Hospital.find params[:hospital_id]
  end

  def new
    @patient = Patient.new
    @hospital = Hospital.find params[:hospital_id]
  end

  def create
    @hospital = Hospital.find params[:hospital_id]
    @patient = @hospital.patients.new(patient_params)
      respond_to do |format|
        if @patient.save
          format.html { redirect_to hospital_path(@hospital), notice: 'Patient Successfully Checked In!' }
        else
          format.html { render :new }
        end
      end
  end

  def edit
    @hospital = Hospital.find params[:hospital_id]
  end

  def destroy
    @hospital = Hospital.find params[:hospital_id]
    @patient.delete
    redirect_to hospitals_path
  end
  
  def update
    @hospital = Hospital.find params[:hospital_id]
    if @patient.update_attributes patient_params
      redirect_to hospitals_path  
    else
      render :edit
    end
  end

 private

  def find_patient
    @patient = Patient.find params[:id]
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :dob, :reason, :gender)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hospitals/_form.html.haml
.jumbotron.formfix
  %center  
    = form_for @hospital do |f|
      %br
        .form-label
          = f.label :name
        .form-group.groupfix
          = f.text_field :name, class: "form-control", placeholder: "Please input the name of your hospital"
        .form-label
          = f.label :address
        .form-group.groupfix
          = f.text_field :address, class: "form-control", placeholder: "Input the address of your location"
        .form-label
          = f.label :description
        .form-group.groupfix
          = f.text_field :description, class: "form-control", placeholder: "Give a brief description of your hospital/specializations"
        = f.submit "Submit", class: "btn btn btn-success"

app/views/hospitals/edit.html.haml
%center  
  %h1 Edit Restaurant

  = render 'form'

app/views/hospitals/index.html.haml
%header#myCarousel.carousel.slide
  / Indicators
  %ol.carousel-indicators
    %li{"data-slide-to" => "0", "data-target" => "#myCarousel"}
    %li.active{"data-slide-to" => "1", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
  / Wrapper for slides
  .carousel-inner
    .item
      .fill{:style => "background-image:url('http://blog.lenycom.com/wp-content/gallery/wallpaper2/1091154011.jpg');"}
      .carousel-caption
        %h2 Appalachian Healthcare
    .item.active
      .fill{:style => "background-image:url('http://patrinos.com/img/1900x1080_pittsburgh_skyline_night.jpg');"}
      .carousel-caption
        %h2 Family Oriented
    .item
      .fill{:style => "background-image:url('http://images.huffingtonpost.com/2013-10-25-Doctor.jpg');"}
      .carousel-caption
        %h2 Dedicated To You
  / Controls
  %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"}
    %span.icon-prev
  %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"}
    %span.icon-next
/ Page Content
.container
  / Marketing Icons Section
  .row
    .col-lg-12
      %h1.page-header
        Welcome to Appalachian Health
    .col-md-4
      .panel.panel-default.divfix
        .panel-heading
          %h4
            %i.fa.fa-fw.fa-check
            Your Health
        .panel-body
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
          %a.btn.btn-default{:href => "#"} Learn More
    .col-md-4
      .panel.panel-default.divfix
        .panel-heading
          %h4
            %i.fa.fa-fw.fa-gift
            Free & Open Source
        .panel-body
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
          = button_to "Add Your Hospital", new_hospital_path, class: "btn btn-success", method: :get
    .col-md-4
      .panel.panel-default.divfix
        .panel-heading
          %h4
            %i.fa.fa-fw.fa-compass
            Easy to Use
        .panel-body
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod?
          %a.btn.btn-default{:href => "#"} Learn More
    %h2.page-header
      Our Providers
    - @hospitals.each do |hospital|
      .col-md-4.col-sm-6
        .col-md-4
        .panel.panel-default.divfix
          .panel-heading
            %h4
              %i.fa.fa-fw.fa-check
              = hospital.name
          .panel-body
            %p
              = truncate(hospital.description, :length => 150)
          .panel-body.buttonfix
            =link_to "View Facility", hospital_path(hospital), class: "btn btn-primary"
  .row
    .col-lg-12
      %h2.page-header Our Research
    .col-md-6
      %p Our research goes above and beyond
      %ul
        %li
          %strong We hire the best healthcare researchers to give you the best care that you need
        %li All are FDA Qualified
        %li Intensive Cancer Research
        %li The Best Pediatric Care Facilities in the US
        %li Health and Fitness Clinics in all of our Facilities
        %li We Live To Make Your Lives Better
      %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.
    .col-md-6
      %img.img-responsive{:alt => "", :src => "http://cdn.therivardreport.com/wp-content/uploads/2015/02/dr.-robert-davey-and-yasuteru-sakurai-700x450.jpg"}/
  / /.row
  %hr/
  / Call to Action Section
  .well
    .row
      .col-md-8
        %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.
      .col-md-4
        %a.btn.btn-lg.btn-default.btn-block{:href => "#"} Call to Action
  %hr/
  / Footer
  %footer
    .row
      .col-lg-12
        %p Copyright © Appalachian Health 2014
/ /.container
/ jQuery

%script{:src => "js/jquery.js"}
/ Bootstrap Core JavaScript
%script{:src => "js/bootstrap.min.js"}
/ Script to Activate the Carousel
:javascript
  $('.carousel').carousel({
      interval: 5000 //changes the speed
  })

app/views/hospitals/new.html.haml
%center  
  %br
  %h1 New Facility

  = render 'form'

app/views/hospitals/show.html.haml
%body
  .container
    / Jumbotron Header
    %header.jumbotron.hero-spacer
      %h1 
        = @hospital.name
      %p 
        = @hospital.description
      %center
        %br
        = link_to "Sign In A Patient", new_hospital_patient_path(@hospital), class: "btn btn-success btn-large"
    %hr/
    / Title
    .row
      .col-lg-12
        %h3 Our Patients
        
      .row.text-center
        - @hospital.patients.each do |patient|
          .col-md-3.col-sm-6.hero-feature
            .thumbnail
              %img{:src => "http://lorempixel.com/800/500/people/#{rand 1..10}"}/
              .caption
                %h3
                  = patient.first_name
                  = patient.last_name
                %p
                  = truncate(patient.reason, :length => 80)
                %p
                  = link_to "View Patient", hospital_patient_path(@hospital, patient), class: "btn btn-sm btn-success"
= form_for @doctor, url: create_doctor_hospital_path(@hospital) do |f|
  = f.label :dr_name, "Add Doctor to Hospital"
  = f.text_field :dr_name
  %br
  = f.submit "Submit", class: "submit_btn", disabled: 'disabled'
%br
%strong
  Doctors
%ul.doctor_list
  - @hospital.doctors.each do |doctor|
    - if doctor.dr_name
      %li
        = doctor.dr_name
        = link_to "Delete Doctor", delete_doctor_hospital_path(@hospital, doctor_id: doctor.id), method: :delete

    %hr
    %center
      = link_to "Edit Hospital", edit_hospital_path(@hospital), class: "btn btn-primary", method: :get
      = link_to "Delete Hospital", hospital_path(@hospital), method: :delete, class: "btn btn-danger"
    %hr
    / Footer
    %footer
      .row
        .col-lg-12
          %p Copyright © Your Website 2014
  / /.container
  / jQuery
  %script{:src => "js/jquery.js"}
  / Bootstrap Core JavaScript
  %script{:src => "js/bootstrap.min.js"}

app/views/layouts/application.html.haml
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
          %meta{:content => "", :name => "description"}
            %meta{:content => "", :name => "author"}
              %title Appalachian Healthcare Group
              = stylesheet_link_tag    'application', media: 'all'
              = javascript_include_tag 'application'
              = csrf_meta_tags
              %link{:href => "css/bootstrap.min.css", :rel => "stylesheet"}
                / Custom CSS
                %link{:href => "css/full-width-pics.css", :rel => "stylesheet"}
                  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
                  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    / Navigation
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"} Appalachian Health
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to "Our Hospitals", hospitals_path
            %li
              %a{:href => "#"} About
            %li
              %a{:href => "#"} Contact
  %body
    = yield

app/views/patients/_form.html.haml
.jumbotron.formfix
  %center  
    = form_for [@hospital, @patient] do |f|
      %br
        .form-label
          = f.label :first_name
        .form-group
          = f.text_field :first_name, class: "form-control", placeholder: "Please input the first name of the patient"
        .form-label
          = f.label :last_name
        .form-group
          = f.text_field :last_name, class: "form-control", placeholder: "Please input the last name of the patient"
        .form-label
          = f.label :dob
          = f.date_select :dob,                   |
            :start_year => Date.today.year - 120, |
            :end_year => Date.today.year + 120,   |
            :order => [:day, :month, :year]       |
        .form-label
          = f.label :reason
        .form-group
          = f.text_area :reason, class: "form-control", placeholder: "Input the symptoms or reason for visit"
        .form-label
          = f.label :gender
          = f.radio_button :gender, 'Male', :checked => true
          = label :male, 'Male'
          = f.radio_button :gender, 'Female'
          = label :gender, 'Female'
          %br
          %br
        .form-label
          = f.submit "Submit", class: "btn btn btn-success"

app/views/patients/edit.html.haml
%center  
  %h1 Edit Patient Information

  = render 'form'

app/views/patients/new.html.haml
%center  
  %br
  %h1 Check-In Patient

  = render 'form'

app/views/patients/show.html.haml
.container
  .row
    .col-md-3
      %p.lead
        - @hospital.patients.each do |patient|
          .thumbnail
            %img{:src => "http://lorempixel.com/800/500/people/#{rand 1..10}"}/
            .caption
              %h3
                = patient.first_name
                = patient.last_name
              %p
                = patient.dob
              %br
                = patient.reason
    .col-md-9
      .thumbnail
        %img.img-responsive{:alt => "", :src => "http://www.verticalvisions.biz/files/2013/05/Ex_Patient_Room-800x300.jpg"}
          .caption-full
            %h4.pull-right=@patient.dob
            %h4
              =@patient.first_name
              =@patient.last_name
            %p
            %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
      .well
        .text-right
          %a.btn.btn-success Workflow states
        %hr
          .row
            .col-md-12
              Workflow state machine under construction!
/ /.container
.container
  %hr
    / Footer
    %footer
      .row
        .col-lg-12
          %p Copyright © Your Website 2014
/ /.container
/ jQuery
%script{:src => "js/jquery.js"}
/ Bootstrap Core JavaScript
%script{:src => "js/bootstrap.min.js"}

app/views/welcome/index.html.haml
%section.module.parallax.parallax-1
  .container
    %h1 Health
%section.module.content
  .container
    %h2 Welcome to Appalachian Health
    %p But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.
%section.module.parallax.parallax-2
  .container
    %h1 Benefits
%section.module.content
  .container
    %h2 What are the Benefits of Appalachian Health?
    %p The master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.
%section.module.parallax.parallax-3
  .container
    %h1 Dedicated
%section.module.content
  .container
    %h2 What we stand for
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
%footer
  .container
    .row
      .col-lg-12
        %p Copyright © Appalachian Health 2014
    / /.row
  / /.container
/ jQuery
%script{:src => "js/jquery.js"}
/ Bootstrap Core JavaScript
%script{:src => "js/bootstrap.min.js"}